#!/usr/bin/env bash
set -eoux pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
app_name=$(basename $(dirname $dir))
image_tag='dev'

cd "${dir}/.."

cp "${dir}/../deploy/default/Dockerfile" Dockerfile

docker build --rm -t $app_name:$image_tag .
docker tag $app_name:$image_tag $app_name

rm Dockerfile
