#!/usr/bin/env bash
set -eoux pipefail

app_name=$(basename $(dirname $(pwd)))
docker_registry='quay.io'
docker_remote="quay.io/skilbjo/$app_name"
email='skilbjo@github.com'

# Use default Dockerfile if one doesn't exist
if [[ ! -f './Dockerfile' ]]
then
  cat '../deploy/default/Dockerfile' | \
    sed "s;__CONSUL_PREFIX__;${consul_prefix};" | \
    sed "s;__CONSUL_SECRET_PREFIX__;${consul_secret_prefix};" \
    > ../Dockerfile
fi

#IMAGE_TAG='latest'
image_tag='dev'

# Login
#docker login -u $QUAY_ROBOT_USERNAME -p $QUAY_ROBOT_PASSWORD -e $EMAIL $DOCKER_REGISTRY

cd ..

# Add git revision
echo $(git rev-parse HEAD) > .tag

# Build
docker build --rm -t $app_name:$image_tag .

# Tag
docker tag $app_name:$image_tag $app_name

# Push it real good
#docker push $docker_remote

# Cleanup
rm Dockerfile
rm .tag
