#!/usr/bin/env bash
set -eou pipefail

resources_dir="resources"

get-jobs(){
  jobs=("$(cat $resources_dir/jobs)")

  for job in "${jobs[@]}"; do
    echo "$job"
  done
}

get-jobs

check-jobs() {
  jobs=("$(cat $resources_dir/jobs)")

  for job in "${jobs[@]}"; do
    local job_state=$(docker ps | grep $job | xargs docker inspect | jq '.[].State')
    local id=$(docker ps | grep $job | xargs docker inspect | jq '.[].State')
    local started_at=$(echo $job_state | jq '.[].State.StartedAt' | xargs date -d +%s)
    local finished_at=$(echo $job_state | jq '.[].State.FinishedAt' | xargs date -d +%s)
    local duration=$(echo "$started_at - $finished_at" | bc)
    local three_days=$(echo "3 * 24 * 60 * 60" | bc)      # in seconds

    if [[ $(echo $job_state | jq '.Running') == "running" ]] && \
      [[ $duration -gt $three_days ]]; then
      echo "job $job is 'running' and up for longer than three days"
    fi
    docker ps --format='table {{.Image}}\t{{.ID}}\t{{.Status}}'
    echo $job
  done
}

restart-job(){
  local id=$1

  docker restart "$id"
}
