#!/usr/bin/env bash
set -eou pipefail

slack() {
  local msg="${1}"

  curl -X POST -H 'Content-type: application/json' \
    --data '{"text":"'"$msg"'"}' \
    https://hooks.slack.com/services/${SLACK_HOOK}
}

email() {
  local msg=$1

  printf "$msg" | mutt -s "Auto kick error at: $(date -I)" -- $distro_list
}

error_handler() {
  local msg="$1"

  email "$msg"
}
