#!/usr/bin/env bash
set -eou pipefail

resources_dir="/usr/local/resources"
src_dir="/usr/local/src"

source "$src_dir/check-jobs"
source "$src_dir/util"
source "$src_dir/error-handling"

monitor() {
  case "$@" in
    hourly)
      jobs="$(cat $resources_dir/jobs)"

      check_jobs $jobs
      ;;
    daily)
      check_jobs
      ;;
    *)
      echo "No arguments given - please provide an argument"; exit 1
      ;;
  esac
}

add_env_vars
monitor "$@"
