#!/usr/bin/env bash

add_env_vars(){
  for var in "$(env)"; do
    export "$var"
  done

  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && \
    chmod 400 ~/.ssh/id_rsa
}

with_backoff() {
  local f="$@"
  set +u
  local max_attempts=${max_attempts:-5}
  local max_timeout_in_mins=${max_timeout_in_mins:-5}
  set -u
  local attempt=1
  local exit_code=0
  local timeout_in_mins=1

  while [[ $attempt -le $max_attempts ]] && [[ $timeout_in_mins -le $max_timeout_in_mins ]]; do
    set +e

    eval $f

    exit_code=$?
    set -e

    if [[ $exit_code == 0 ]]; then
      break
    fi

    sleep $(echo "(($timeout_in_mins * 60))" | bc)
    attempt=$(( attempt + 1 ))
    timeout_in_mins=$(( timeout_in_mins * 2 ))
  done

  if [[ $exit_code != 0 ]]; then
    echo "You've failed me for the last time! ($@)" 1>&2
  fi

  return $exit_code
}
